/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAkunRouteImport } from './routes/admin.akun'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminPesanRouteImport } from './routes/admin.pesan'
import { Route as AdminRekapRouteImport } from './routes/admin.rekap'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesBroadcastRouteImport } from './routes/sales.broadcast'
import { Route as SalesKolamMinatRouteImport } from './routes/sales.kolam-minat'
import { Route as SalesNoteRouteImport } from './routes/sales.note'
import { Route as SalesRiwayatRouteImport } from './routes/sales.riwayat'
import { Route as SalesCustomersIndexRouteImport } from './routes/sales.customers.index'
import { Route as SalesCustomersIdRouteImport } from './routes/sales.customers.$id'
import { Route as SalesCustomersDetailsRouteImport } from './routes/sales.customers.details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAkunRoute = AdminAkunRouteImport.update({
  id: '/admin/akun',
  path: '/admin/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesanRoute = AdminPesanRouteImport.update({
  id: '/admin/pesan',
  path: '/admin/pesan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRekapRoute = AdminRekapRouteImport.update({
  id: '/admin/rekap',
  path: '/admin/rekap',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesBroadcastRoute = SalesBroadcastRouteImport.update({
  id: '/sales/broadcast',
  path: '/sales/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesKolamMinatRoute = SalesKolamMinatRouteImport.update({
  id: '/sales/kolam-minat',
  path: '/sales/kolam-minat',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNoteRoute = SalesNoteRouteImport.update({
  id: '/sales/note',
  path: '/sales/note',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRiwayatRoute = SalesRiwayatRouteImport.update({
  id: '/sales/riwayat',
  path: '/sales/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersIndexRoute = SalesCustomersIndexRouteImport.update({
  id: '/sales/customers/',
  path: '/sales/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersIdRoute = SalesCustomersIdRouteImport.update({
  id: '/sales/customers/$id',
  path: '/sales/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersDetailsRoute = SalesCustomersDetailsRouteImport.update({
  id: '/sales/customers/details',
  path: '/sales/customers/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/akun': typeof AdminAkunRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/rekap': typeof AdminRekapRoute
  '/sales/broadcast': typeof SalesBroadcastRoute
  '/sales/kolam-minat': typeof SalesKolamMinatRoute
  '/sales/note': typeof SalesNoteRoute
  '/sales/riwayat': typeof SalesRiwayatRoute
  '/admin/': typeof AdminIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/customers/details': typeof SalesCustomersDetailsRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/akun': typeof AdminAkunRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/rekap': typeof AdminRekapRoute
  '/sales/broadcast': typeof SalesBroadcastRoute
  '/sales/kolam-minat': typeof SalesKolamMinatRoute
  '/sales/note': typeof SalesNoteRoute
  '/sales/riwayat': typeof SalesRiwayatRoute
  '/admin': typeof AdminIndexRoute
  '/sales': typeof SalesIndexRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/customers/details': typeof SalesCustomersDetailsRoute
  '/sales/customers': typeof SalesCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/akun': typeof AdminAkunRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/rekap': typeof AdminRekapRoute
  '/sales/broadcast': typeof SalesBroadcastRoute
  '/sales/kolam-minat': typeof SalesKolamMinatRoute
  '/sales/note': typeof SalesNoteRoute
  '/sales/riwayat': typeof SalesRiwayatRoute
  '/admin/': typeof AdminIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/customers/details': typeof SalesCustomersDetailsRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/akun'
    | '/admin/data'
    | '/admin/pesan'
    | '/admin/rekap'
    | '/sales/broadcast'
    | '/sales/kolam-minat'
    | '/sales/note'
    | '/sales/riwayat'
    | '/admin/'
    | '/sales/'
    | '/sales/customers/$id'
    | '/sales/customers/details'
    | '/sales/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/akun'
    | '/admin/data'
    | '/admin/pesan'
    | '/admin/rekap'
    | '/sales/broadcast'
    | '/sales/kolam-minat'
    | '/sales/note'
    | '/sales/riwayat'
    | '/admin'
    | '/sales'
    | '/sales/customers/$id'
    | '/sales/customers/details'
    | '/sales/customers'
  id:
    | '__root__'
    | '/'
    | '/admin/akun'
    | '/admin/data'
    | '/admin/pesan'
    | '/admin/rekap'
    | '/sales/broadcast'
    | '/sales/kolam-minat'
    | '/sales/note'
    | '/sales/riwayat'
    | '/admin/'
    | '/sales/'
    | '/sales/customers/$id'
    | '/sales/customers/details'
    | '/sales/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAkunRoute: typeof AdminAkunRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminPesanRoute: typeof AdminPesanRoute
  AdminRekapRoute: typeof AdminRekapRoute
  SalesBroadcastRoute: typeof SalesBroadcastRoute
  SalesKolamMinatRoute: typeof SalesKolamMinatRoute
  SalesNoteRoute: typeof SalesNoteRoute
  SalesRiwayatRoute: typeof SalesRiwayatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SalesCustomersIdRoute: typeof SalesCustomersIdRoute
  SalesCustomersDetailsRoute: typeof SalesCustomersDetailsRoute
  SalesCustomersIndexRoute: typeof SalesCustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/akun': {
      id: '/admin/akun'
      path: '/admin/akun'
      fullPath: '/admin/akun'
      preLoaderRoute: typeof AdminAkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pesan': {
      id: '/admin/pesan'
      path: '/admin/pesan'
      fullPath: '/admin/pesan'
      preLoaderRoute: typeof AdminPesanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rekap': {
      id: '/admin/rekap'
      path: '/admin/rekap'
      fullPath: '/admin/rekap'
      preLoaderRoute: typeof AdminRekapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/broadcast': {
      id: '/sales/broadcast'
      path: '/sales/broadcast'
      fullPath: '/sales/broadcast'
      preLoaderRoute: typeof SalesBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/kolam-minat': {
      id: '/sales/kolam-minat'
      path: '/sales/kolam-minat'
      fullPath: '/sales/kolam-minat'
      preLoaderRoute: typeof SalesKolamMinatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/note': {
      id: '/sales/note'
      path: '/sales/note'
      fullPath: '/sales/note'
      preLoaderRoute: typeof SalesNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/riwayat': {
      id: '/sales/riwayat'
      path: '/sales/riwayat'
      fullPath: '/sales/riwayat'
      preLoaderRoute: typeof SalesRiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers/': {
      id: '/sales/customers/'
      path: '/sales/customers'
      fullPath: '/sales/customers/'
      preLoaderRoute: typeof SalesCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers/$id': {
      id: '/sales/customers/$id'
      path: '/sales/customers/$id'
      fullPath: '/sales/customers/$id'
      preLoaderRoute: typeof SalesCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers/details': {
      id: '/sales/customers/details'
      path: '/sales/customers/details'
      fullPath: '/sales/customers/details'
      preLoaderRoute: typeof SalesCustomersDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAkunRoute: AdminAkunRoute,
  AdminDataRoute: AdminDataRoute,
  AdminPesanRoute: AdminPesanRoute,
  AdminRekapRoute: AdminRekapRoute,
  SalesBroadcastRoute: SalesBroadcastRoute,
  SalesKolamMinatRoute: SalesKolamMinatRoute,
  SalesNoteRoute: SalesNoteRoute,
  SalesRiwayatRoute: SalesRiwayatRoute,
  AdminIndexRoute: AdminIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  SalesCustomersIdRoute: SalesCustomersIdRoute,
  SalesCustomersDetailsRoute: SalesCustomersDetailsRoute,
  SalesCustomersIndexRoute: SalesCustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
